spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/bank
    username: root
    password: Lider77@

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    enabled: true

app:
  server:
    url: localhost:8080

